<?php
/**
 * Copyright (c) 2017 CardGate B.V.
 * All rights reserved.
 * See LICENSE for license details.
 */
?>
<dl class="payment-method purchase order">
	<dt class="title"><?php echo $block->escapeHtml( $block->getMethod()->getTitle() ) ?> by CardGate</dt>
	<dt class="content"><strong><?php echo $block->escapeHtml( __( 'Transaction Id' ) ) ?></strong> <?php echo $block->escapeHtml( $block->getInfo()->getCardgateTransaction() ) ?></dt>
</dl>
